Repository 2024-SMHRD-DCX-BigData-16/jobis_git, pull requests merged in 2025-04, with the labels that each got.

#2 maenghun_commit
  src/main.py
Labels: documentation, enhancement, good first issue

#5 status modified
  src/main.py
Labels: duplicate

#4 Feature/add
  src/asd.py
  src/main.py
Labels: enhancement
